type: medusa
target_model: 
  base: "lmsys/vicuna-7b-v1.3"
  medusa: "FasterDecoding/medusa-vicuna-7b-v1.3"
generate_args:
  temperature: 0.7
  posterior_threshold: 0.09
  posterior_alpha: 0.3
  max_length: 512
  medusa_choices: [0,1,2]