vllm_model:
  model: "meta-llama/Llama-3.1-8B-Instruct"
  tensor_parallel_size: 1 
  max_model_len: 75136 # had to infer from the error logs
  speculative_config:
    model: "meta-llama/Llama-3.2-1B-Instruct"
    num_speculative_tokens: 5

sampling_params:
  temperature: 0.8
  top_p: 0.95

generate_args:
  max_new_tokens: 128