type: eagle2
target_model: meta-llama/Llama-3.1-8b-Instruct
draft_model: meta-llama/Llama-3.2-1b-Instruct
generate_args:
  max_new_tokens: 50
  temperature: 0.7
  top_k: 0
  top_p: 0.9
  num_draft_tokens: 5
  acceptance_threshold: 0.3