type: eagle2
target_model: google/gemma-7b
draft_model: google/gemma-2b-it
generate_args:
  max_new_tokens: 32
  temperature: 0.7
  top_k: 0
  top_p: 0.9
  num_draft_tokens: 5  # Number of tokens to generate in each draft step
  acceptance_threshold: 0.3  # Probability threshold for accepting draft tokens 