type: fsd
target_model: meta-llama/Llama-3.1-8B-Instruct
draft_model: meta-llama/Llama-3.2-1B-Instruct
generate_args:
  fsd_div_threshold: 0.4
  fsd_div_type: js_div
  max_new_tokens: 50
  do_sample: false