methods: 
  - /insomnia001/depts/edu/COMSE6998/aa5506/Speculative-Decoding/benchmarks/configs/fsd.yml
  - /insomnia001/depts/edu/COMSE6998/aa5506/Speculative-Decoding/benchmarks/configs/spec-decoding.yml

speedup: ./cluster_speedup.json

benchmark:
  dataset: /insomnia001/depts/edu/COMSE6998/aa5506/Speculative-Decoding/data/ultrachat_5000_prompts_clustered.jsonl
  max_new_tokens: 50

interactive:
  kmeans: /insomnia001/depts/edu/COMSE6998/aa5506/Speculative-Decoding/data/kmeans_model_uc.joblib
  sentence_model: all-MiniLM-L6-v2
  default: fsd
  max_new_tokens: 1024