methods: 
  - name: baseline
    file: ../benchmarks/out/results_naive_smol.json
  - name: fsd
    file: ../benchmarks/out/results_fsd_smol.json
  - name: spec-decoding
    file: ../benchmarks/out/results_spec-decoding_smol.json